export default {
    PRIMARYCOLOR:'#659AB3',
    LIGHTPRIMARYCOLOR:'#7DBFDE',
    WHITE: '#FFF',
    WHITESECONDARY: '#F2F1F1',
    SECONDARY: '#FFF',
    BLACK: '#0F0F0F',
    BLACKSECONDARY: '#371402',
    BLUE: '#377bff',
    GRAY: '#9E9E9E',
    RED: '#D32F2F',
    LIGHTGREEN: '#d4edda',
};